version: "3"
services:
  prometheus:
   image: "prom/prometheus:v2.30.3"
   volumes:
    #  - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    #  - "~/.aws:/home/.aws"
    #  - "./alert.rules:/alert.rules"
    - ./prometheus:/etc/prometheus
   command:
    - "--config.file=/etc/prometheus/prometheus.yml"
    - "--web.enable-lifecycle"
   ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
  alertmanager:
    image: bitnami/alertmanager
    volumes:
      - "./alertmanager.yml:/etc/alertmanager/alertmanager.yml"
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    ports:
      - '9093:9093'
    depends_on:
      - prometheus