global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
rule_files:
  - "alerts.rules"
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['host.docker.internal:9090']
  - job_name: alertmanager
    static_configs:
    - targets: ['host.docker.internal:9093']
  - job_name: Grafana
    static_configs:
    - targets: ['host.docker.internal:3000']
  - job_name: jenkins
    metrics_path: /prometheus
    static_configs:
    - targets: ['host.docker.internal:8080']
